[tool.poetry]
name = "CaseReview"
version = "0.1.0"
description = ""
authors = ["patarapolw <patarapolw@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
flask = "^1.0"
jupyter = "^1.0"
notebook = "^5.6"
flask_sqlalchemy = "^2.3"
python-dateutil = "^2.7"

[tool.poetry.dev-dependencies]
